server.port=8082

jwt.secret=sjvsfkjvhiucvswnfvuiwshfiurhiugfvh4
#microservice.local.database.name=arisebh
microservice.local.database.name=shishukunjnc
#microservice.local.database.name=kps
#microservice.local.database.name=dalycollege
microservice.local.database.port=3306
microservice.local.database.password=hrhk
microservice.local.database.username=root
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.data.redis.port=6379
#spring.data.redis.password=
#spring.data.redis.sentinel.master=mymaster
#spring.data.redis.sentinel.nodes=localhost
#spring.cache.type=redis
#spring.cache.redis.cache-null-values=false
#spring.cache.redis.time-to-live=300000
#spring.data.redis.timeout=600ms


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


server.max-http-request-header-size=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

